### ISSUE TITLE
Uknown argument when trying to specify port

### ISSUE THREAD

**Issue by keirlawson** [smithy-lang/smithy-language-server#143]
When launching the latest version of the language server using coursier using a specified port I get an unknown argument error and the server does not launch.  This is a regression from 0.2.3 which does work.

```
cs launch --contrib smithy-language-server:0.2.4 -- 0
Unknown argument or command: 0
```

**Comment by milesziemer** [comment]
Try specifying the main class:
```
cs launch --contrib smithy-language-server:0.2.4 -M software.amazon.smithy.lsp.Main -- 0
```
I think coursier is trying to execute the smithy-cli, which is a dependency of (and packaged with) the language server.
