### ISSUE TITLE
Performance problems in large codebases

### ISSUE THREAD

**Issue by kubukoz** [smithy-lang/smithy-language-server#145]
Hi! 

My team maintains a "specbase" of about 1200 Smithy files, containing about 6700 non-member shapes. In the recent months, as the repository has grown, we've started noticing significant performance problems - which keep growing.

Here's a real-time recording of me trying to add a small structure to the model.

https://github.com/smithy-lang/smithy-language-server/assets/894884/7dd0c874-26f8-45d1-a8e6-451fa7334ee8

As you can see, all the feedback is significantly delayed. An educated guess is that this is due to a combination of the following:

- lots of shapes (obviously, but arguably even 10k shapes isn't that much when you compare it to Java class counts in an average codebase, for example)
- some suboptimal validators (e.g. https://github.com/disneystreaming/smithy4s/issues/1319)
- the LSP server loading & validating the model on every `textDocument/didChange` notification
- lack of cancellation support in the server.

Can we make some steps to improve the situation? I have these suggestions right off the bat:

1. Handle cancellation of requests
2. Deduplicate concurrent `didChange` notifications (or perhaps just loading the model concurrently altogether)
3. Consider not reloading the model on `didChange`, doing it only in `didSave` instead.

**Comment by Baccata** [comment]
> Consider not reloading the model on didChange, doing it only in didSave instead. 

I think this should be pursued no matter what : recompiling on `didChange` is a pretty bad pattern.

**Comment by Baccata** [comment]
From what I gather, the current behaviour of `didChange` stores the buffered contents into a [map](https://github.com/smithy-lang/smithy-language-server/blob/c7931522c11c8b07a8a6eb13ecfad5370c18206e/src/main/java/software/amazon/smithy/lsp/SmithyTextDocumentService.java#L643), such that completion requests can retrieve the [token that's being edited](https://github.com/smithy-lang/smithy-language-server/blob/c7931522c11c8b07a8a6eb13ecfad5370c18206e/src/main/java/software/amazon/smithy/lsp/SmithyTextDocumentService.java#L229), before looking it up in the collection of known shapes. 

So I think removing the [recompilation and reporting](https://github.com/smithy-lang/smithy-language-server/blob/c7931522c11c8b07a8a6eb13ecfad5370c18206e/src/main/java/software/amazon/smithy/lsp/SmithyTextDocumentService.java#L654) instruction from the `didChange` implementation would suffice to drastically improve performance.

**Comment by kubukoz** [comment]
Can we have some direction on this? I would start with @Baccata's suggestion.

**Comment by milesziemer** [comment]
Yea that's pretty bad. All the suggestions sound like viable solutions - but I think LSP4J can actually handle the first two for us. I looked through their docs and some old issues, and found [this](https://github.com/eclipse-lsp4j/lsp4j/issues/775#issuecomment-1858131056). It looks like most if not all request/notification handler methods do all their work synchronously, so sequential didChange (or any event) just pile up if they don't complete right away. The easiest thing to try I think would be what that issue suggests, wrap our didChange in a CompletableFuture:
```
@Override
public void didChange(DidChangeTextDocumentParams params) {
    CompletableFuture.runAsync(() -> {
        // ... Current method body
    });
}
```

I need to set up a large code base to see what impact this has. I'll do this now. It might require some other changes elsewhere to make sure everything works asynchronously.

In regards to 3:
> Consider not reloading the model on didChange, doing it only in didSave instead.

and
> I think this should be pursued no matter what : recompiling on didChange is a pretty bad pattern.

Yea I agree mostly, recompiling on _every_ change is definitely a huge waste. I think the issues it causes though can mostly be addressed by not blocking each subsequent didChange events on the completion of each prior event. We can still recompile on change, but if we can cancel that action when a new didChange notification comes in and start a new one, it shouldn't ever lag like in the video. And you maintain functionality of other features like getting diagnostics for what you've written without needing to save.

**Comment by Baccata** [comment]
> syntax errors are fair game I think, and mayybe loading the model with no external validators (maybe this part could be configurable?), but I'd say we should save validators for the didSave notification.

If it was me, I'd tackle it iteratively : separating the "basic" validation from the validators will probably require more code. 

> As for cancellation, that might work, but the code probably needs to be aware of InterruptedException (I'm not 100% sure, haven't worked with that side of Java a lot to be honest)

I don't think @milesziemer was talking about proper cancellation (as in interrupting an ongoing procedure), more about debouncing (which is a common practice when key-strokes are involved). You essentially schedule a callback to trigger after a small duration (could be something like 2 seconds), and if new events come before the timer has expired, you un-schedule the previous callback and schedule a new one. See [an example of java debouncer](https://stackoverflow.com/questions/4742210/implementing-debounce-in-java/20978973#20978973).

**Comment by Baccata** [comment]
To be clear : unlike @kubukoz's, my organisation doesn't run the adtMember validator in our large smithy repo, and still experiences the sluggishness of the editor. Though I can certainly accept that optimising validators is a worthwhile endeavour, I still think that removing the compilation on "didChange" or at least debouncing it (to prevent multiple successive expensive runs) would be easily achieved and very beneficial.

**Comment by milesziemer** [comment]
I've just put up a PR that should address this issue as best we can short-term (not to undersell the improvements - but we can still do better). It has a combination of the ideas in this issue - thank you for the suggestions. This won't build locally right now (it needs some Smithy changes), but when it can, you're welcome to build it locally and see how it is. I'll give an update when that's possible (and instructions to do so, probably a readme entry). Thanks for your patience

**Comment by milesziemer** [comment]
With https://github.com/smithy-lang/smithy-language-server/pull/146 was released in https://github.com/smithy-lang/smithy-language-server/releases/tag/0.4.0, I will close this. Feel free to re-open if you are still having issues.
