### ISSUE TITLE
Language server conflicts with Local History

### ISSUE THREAD

**Issue by seebees** [smithy-lang/smithy-language-server#156]
I use https://marketplace.visualstudio.com/items?itemName=xyz.local-history. It is helpful to have a local copy of all my changes. It has saved me a few times when I did not commit aggressively enough :) It stores the backups in a `.history` folder in the root of the project.

The problem is that the language server just slurps up all *.smithy files under the project. It gives me a lot of `Model: Conflicting shape definition for` errors. Because obviously there are conflicts in files that are copies :)

My guess is that the real feature in here is not so much this plugin per se as having the  language server honor `.gitignore`. But I will leave that to you. Feel free to change the title or anything if you agree.

**Comment by milesziemer** [comment]
This is fixed in https://github.com/smithy-lang/smithy-language-server/pull/146
