### ISSUE TITLE
Improve locations of diagnostics

### ISSUE THREAD

**Issue by milesziemer** [smithy-lang/smithy-language-server#76]
Diagnostics do not include all of the text they are referring to, like in this example:
![poorly-placed-diagnostics](https://user-images.githubusercontent.com/45497130/195353814-02660cfc-6b1f-42f1-80e8-e483366b3f78.png)
The diagnostics under `use` and `structure` should extend to cover the rest of the text.

**Comment by milesziemer** [comment]
Here's another example:
![image](https://github.com/user-attachments/assets/c2945e04-ed6b-4e45-bb24-e56ffba52a8e)
![image](https://github.com/user-attachments/assets/3baa358b-4c78-4131-8546-431867d2d4de)

Preferably, the error would be right after the `abc`. The current strategy for determining the range to apply the diagnostic to is [here](https://github.com/smithy-lang/smithy-language-server/blob/b4257161f8ad037fa6b89be66813032d330be227/src/main/java/software/amazon/smithy/lsp/SmithyLanguageServer.java#L790). `ValidationEvent`s are a 1-based line/column point, so we put the event from the line start, up to and including that point. At the time, this was probably the simplest way to get mostly relevant diagnostic locations, but we can do better.

One idea would be to make the validation event on the 'token' at the `ValidationEvent` point. If we're in whitespace, it could be just a single character at that point. If we make the 'token' just be contiguous text, I think we would cover most cases, at least better than right now. We can always customize specific validation events, if necessary.

**Comment by yasmewad** [comment]
Closing as it is solved as part of https://github.com/smithy-lang/smithy-language-server/pull/179
